version: '3'

tasks:
  check-deps:
    internal: true
    desc: Check if required dependencies are installed
    cmds:
      - |
        #!/usr/bin/env bash
        set -e
        missing=""
        for cmd in protoc protoc-gen-go protoc-gen-go-grpc protoc-gen-connect-go protoc-gen-rpc-cgo-adaptor protoc-gen-rpc-cgo; do
          if ! command -v "$cmd" >/dev/null 2>&1; then
            missing="$missing"$'\n'"  - $cmd"
          fi
        done
        if [ -n "$missing" ]; then
          echo "❌ Missing required dependencies:$missing"
          echo ""
          echo "Install with:"
          echo "  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
          echo "  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest"
          echo "  go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest"
          echo "  go install github.com/ygrpc/rpccgo/cmd/protoc-gen-rpc-cgo-adaptor@latest"
          echo "  go install github.com/ygrpc/rpccgo/cmd/protoc-gen-rpc-cgo@latest"
          exit 1
        fi

  test:
    desc: Run full test suite (adaptor + C tests)
    deps: [check-deps]
    cmds:
      - ./test.sh

  adaptor-test:
    desc: Run adaptor tests (default all, or specify grpc|connect|mix|connect_suffix)
    deps: [check-deps]
    cmds:
      - ./run-adaptor-tests.sh {{.PROTOCOL}}
    vars:
      PROTOCOL: '{{.PROTOCOL | default "all"}}'
    preconditions:
      - sh: bash -c '[[ "{{.PROTOCOL}}" =~ ^(all|grpc|connect|mix|connect_suffix)$ ]]'
        msg: 'Invalid PROTOCOL "{{.PROTOCOL}}". Must be one of: all, grpc, connect, mix, connect_suffix'

  c-test:
    desc: Run C end-to-end tests (default all, or specify grpc|connect|mix|connect_suffix)
    deps: [check-deps]
    cmds:
      - ./run-c-tests.sh {{.PROTOCOL}}
    vars:
      PROTOCOL: '{{.PROTOCOL | default "all"}}'
    preconditions:
      - sh: bash -c '[[ "{{.PROTOCOL}}" =~ ^(all|grpc|connect|mix|connect_suffix)$ ]]'
        msg: 'Invalid PROTOCOL "{{.PROTOCOL}}". Must be one of: all, grpc, connect, mix, connect_suffix'

  build:
    desc: Build adaptor code for protocol (default connect, or specify grpc|connect|mix|connect_suffix)
    deps: [check-deps]
    cmds:
      - |
        case "{{.PROTOCOL}}" in
          connect_suffix) ./build-connect-suffix.sh ;;
          *) ./build-{{.PROTOCOL}}.sh ;;
        esac
    vars:
      PROTOCOL: '{{.PROTOCOL | default "connect"}}'
    preconditions:
      - sh: bash -c '[[ "{{.PROTOCOL}}" =~ ^(grpc|connect|mix|connect_suffix)$ ]]'
        msg: 'Invalid PROTOCOL "{{.PROTOCOL}}". Must be one of: grpc, connect, mix, connect_suffix'

  build-cgo:
    desc: Build C ABI export for protocol (default connect, or specify grpc|connect|mix|connect_suffix)
    deps: [check-deps]
    cmds:
      - |
        case "{{.PROTOCOL}}" in
          connect_suffix) ./build-cgo-connect-suffix.sh ;;
          *) ./build-cgo-{{.PROTOCOL}}.sh ;;
        esac
    vars:
      PROTOCOL: '{{.PROTOCOL | default "connect"}}'
    preconditions:
      - sh: bash -c '[[ "{{.PROTOCOL}}" =~ ^(grpc|connect|mix|connect_suffix)$ ]]'
        msg: 'Invalid PROTOCOL "{{.PROTOCOL}}". Must be one of: grpc, connect, mix, connect_suffix'
