// Code generated by protoc-gen-rpc-cgo-adaptor. DO NOT EDIT.
//
// source: unary.proto
// protocol: grpc

package cgotest_grpc

import (
	context "context"
	rpcruntime "github.com/ygrpc/rpccgo/rpcruntime"
)

// TestService_Ping_Grpc calls cgotest.TestService.Ping via grpc handler.
func TestService_Ping_Grpc(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	h, ok := rpcruntime.LookupGrpcHandler("cgotest.TestService")
	if !ok {
		return nil, rpcruntime.ErrServiceNotRegistered
	}
	svc, ok := h.(TestServiceServer)
	if !ok {
		return nil, rpcruntime.ErrHandlerTypeMismatch
	}
	return svc.Ping(ctx, req)
}

// TestService_PingOpt1_Grpc calls cgotest.TestService.PingOpt1 via grpc handler.
func TestService_PingOpt1_Grpc(ctx context.Context, req *PingRequestOpt1) (*PingResponse, error) {
	h, ok := rpcruntime.LookupGrpcHandler("cgotest.TestService")
	if !ok {
		return nil, rpcruntime.ErrServiceNotRegistered
	}
	svc, ok := h.(TestServiceServer)
	if !ok {
		return nil, rpcruntime.ErrHandlerTypeMismatch
	}
	return svc.PingOpt1(ctx, req)
}

// TestService_PingOpt2_Grpc calls cgotest.TestService.PingOpt2 via grpc handler.
func TestService_PingOpt2_Grpc(ctx context.Context, req *PingRequestOpt2) (*PingResponse, error) {
	h, ok := rpcruntime.LookupGrpcHandler("cgotest.TestService")
	if !ok {
		return nil, rpcruntime.ErrServiceNotRegistered
	}
	svc, ok := h.(TestServiceServer)
	if !ok {
		return nil, rpcruntime.ErrHandlerTypeMismatch
	}
	return svc.PingOpt2(ctx, req)
}

// TestService_NonFlat_Grpc calls cgotest.TestService.NonFlat via grpc handler.
func TestService_NonFlat_Grpc(ctx context.Context, req *NonFlatRequest) (*PingResponse, error) {
	h, ok := rpcruntime.LookupGrpcHandler("cgotest.TestService")
	if !ok {
		return nil, rpcruntime.ErrServiceNotRegistered
	}
	svc, ok := h.(TestServiceServer)
	if !ok {
		return nil, rpcruntime.ErrHandlerTypeMismatch
	}
	return svc.NonFlat(ctx, req)
}
