// Code generated by protoc-gen-rpc-cgo-adaptor. DO NOT EDIT.
//
// source: unary.proto
// protocol: connectrpc

package cgotest_connect

import (
	context "context"
	rpcruntime "github.com/ygrpc/rpccgo/rpcruntime"
)

// TestService_Ping_Connectrpc calls cgotest.TestService.Ping via connectrpc handler.
func TestService_Ping_Connectrpc(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	h, ok := rpcruntime.LookupConnectHandler("cgotest.TestService")
	if !ok {
		return nil, rpcruntime.ErrServiceNotRegistered
	}
	svc, ok := h.(TestServiceHandler)
	if !ok {
		return nil, rpcruntime.ErrHandlerTypeMismatch
	}
	return svc.Ping(ctx, req)
}

// TestService_PingOpt1_Connectrpc calls cgotest.TestService.PingOpt1 via connectrpc handler.
func TestService_PingOpt1_Connectrpc(ctx context.Context, req *PingRequestOpt1) (*PingResponse, error) {
	h, ok := rpcruntime.LookupConnectHandler("cgotest.TestService")
	if !ok {
		return nil, rpcruntime.ErrServiceNotRegistered
	}
	svc, ok := h.(TestServiceHandler)
	if !ok {
		return nil, rpcruntime.ErrHandlerTypeMismatch
	}
	return svc.PingOpt1(ctx, req)
}

// TestService_PingOpt2_Connectrpc calls cgotest.TestService.PingOpt2 via connectrpc handler.
func TestService_PingOpt2_Connectrpc(ctx context.Context, req *PingRequestOpt2) (*PingResponse, error) {
	h, ok := rpcruntime.LookupConnectHandler("cgotest.TestService")
	if !ok {
		return nil, rpcruntime.ErrServiceNotRegistered
	}
	svc, ok := h.(TestServiceHandler)
	if !ok {
		return nil, rpcruntime.ErrHandlerTypeMismatch
	}
	return svc.PingOpt2(ctx, req)
}

// TestService_NonFlat_Connectrpc calls cgotest.TestService.NonFlat via connectrpc handler.
func TestService_NonFlat_Connectrpc(ctx context.Context, req *NonFlatRequest) (*PingResponse, error) {
	h, ok := rpcruntime.LookupConnectHandler("cgotest.TestService")
	if !ok {
		return nil, rpcruntime.ErrServiceNotRegistered
	}
	svc, ok := h.(TestServiceHandler)
	if !ok {
		return nil, rpcruntime.ErrHandlerTypeMismatch
	}
	return svc.NonFlat(ctx, req)
}
